# Generated by Django 6.0.2 on 2026-03-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.AutoField(db_column='bookId', primary_key=True, serialize=False)),
                ('goodreadsbookid', models.IntegerField(db_column='goodreadsBookId')),
                ('isbn', models.IntegerField()),
                ('authors', models.TextField()),
                ('title', models.TextField()),
                ('averagerating', models.FloatField(db_column='averageRating')),
                ('weightedscore', models.FloatField(db_column='weightedScore')),
                ('ratingscount', models.IntegerField(db_column='ratingsCount')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['bookid'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genreid', models.AutoField(db_column='genreId', primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['genreid'],
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('pk', models.CompositePrimaryKey('bookida', 'bookidb', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bookida', models.IntegerField(db_column='bookIdA')),
                ('bookidb', models.IntegerField(db_column='bookIdB')),
                ('averagerating', models.FloatField(db_column='averageRating')),
                ('sumrating', models.IntegerField(db_column='sumRating')),
                ('ratingscount', models.TextField(db_column='ratingsCount')),
                ('weightedscore', models.FloatField(db_column='weightedScore')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.CASCADE, to='api.books')),
                ('genreid', models.ForeignKey(db_column='genreId', on_delete=django.db.models.deletion.CASCADE, to='api.genres')),
            ],
            options={
                'db_table': 'book_genre',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(through='api.BookGenre', to='api.genres'),
        ),
    ]
