# Generated by Django 6.0.2 on 2026-03-03 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefinished', models.DateField()),
                ('bookid', models.ForeignKey(db_column='bookId', on_delete=django.db.models.deletion.CASCADE, to='api.books')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'book_user',
                'ordering': ['userid', 'bookid'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='readby',
            field=models.ManyToManyField(through='api.BookUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
