# Generated by Django 6.0.2 on 2026-03-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_books_isbn_bookuser_books_readby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'managed': False, 'ordering': ['bookid']},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False, 'ordering': ['genreid']},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': False},
        ),
    ]
