# Generated by Django 6.0.2 on 2026-03-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bookgenre_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookuser',
            options={'ordering': ['user', 'book']},
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='bookid',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='userid',
            new_name='user',
        ),
    ]
