# Generated by Django 6.0.2 on 2026-03-05 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bookuser_options_rename_bookid_bookuser_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together={('user', 'book')},
        ),
    ]
