# Generated by Django 6.0.2 on 2026-03-05 07:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bookuser_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookuser',
            options={'ordering': ['userid', 'bookid']},
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='book',
            new_name='bookid',
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='user',
            new_name='userid',
        ),
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together={('userid', 'bookid')},
        ),
    ]
