# Generated by Django 6.0.2 on 2026-03-05 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bookuser_options_rename_book_bookuser_bookid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookuser',
            options={'ordering': ['user', 'book']},
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='bookid',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='bookuser',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together={('user', 'book')},
        ),
    ]
