# Generated by Django 6.0.2 on 2026-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bookuser_options_rename_bookid_bookuser_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookuser',
            name='datefinished',
            field=models.DateField(null=True),
        ),
    ]
