# Generated by Django 6.0.2 on 2026-03-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bookuser_datefinished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['bookid']},
        ),
    ]
