# Generated by Django 6.0.2 on 2026-03-19 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_books_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='coverid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='api.BookGenre', to='api.genres'),
        ),
        migrations.AlterField(
            model_name='books',
            name='readby',
            field=models.ManyToManyField(related_name='books', through='api.BookUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
