# Generated by Django 6.0.2 on 2026-03-26 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_books_coverid_alter_books_genres_alter_books_readby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='bookuser',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='bookuser_record'),
        ),
    ]
