# Generated by Django 6.0.2 on 2026-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_bookuser_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookuser',
            name='bookuser_record',
        ),
    ]
