# Generated by Django 6.0.2 on 2026-03-26 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_bookuser_bookuser_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookuser',
            constraint=models.UniqueConstraint(fields=('book', 'user'), name='bookuser_record'),
        ),
    ]
